manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

# To use TracIK, install moveit-kinematics and change to:
# kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin

# To use IKFast, you must generate an IKFast plugin for your robot and change to:
# kinematics_solver: <my_robot_name>_manipulator_kinematics/IKFastKinematicsPlugin
